# Generated by Django 3.0.3 on 2020-02-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaldata',
            old_name='stock',
            new_name='symbol',
        ),
    ]
