# Generated by Django 3.0.3 on 2020-02-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_auto_20200227_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='open',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='time',
            field=models.DateTimeField(default=1582838451.6715107),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
