# Generated by Django 3.0.3 on 2020-02-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_auto_20200227_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimedata',
            name='time',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
        ),
    ]
