# Generated by Django 3.0.3 on 2020-02-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_auto_20200227_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalData',
        ),
        migrations.DeleteModel(
            name='RealtimeData',
        ),
    ]
